### PR TITLE
Add support for Qt 6

### PR DESCRIPTION
**Pull request by visuve**
- The ``build_qt6.sh`` is pretty much a clone of the ``build_qt5.sh`` as the CMake files are now made a bit better

### CODE REVIEW

**Comment by visuve** [comment]
@hasherezade unfortunately I cannot get the [pe-bear](https://github.com/hasherezade/pe-bear) to compile on Qt 4, 5 and 6 guaranteeing each will work.

I got quite far with the Qt5 compatibility module (when building on Qt6), but here is the problem depicted in a table:

|      |      QRegExp     | QRegExpValidator | QRegularExpression | QRegularExpressionValidator |
|:----:|:----------------:|:----------------:|:------------------:|:---------------------------:|
| Qt 4 |        Yes       |        Yes       |         No         |              No             |
| Qt 5 |        Yes       |        Yes       |         Yes        |             Yes             |
| Qt 6 | Yes (Qt5 compat) |        No        |         Yes        |             Yes             |

So... I strongly suggest to just drop the support for Qt 4 as the last release (Qt 4.8.7) was 26th of May 2015...

**Comment by hasherezade** [comment]
Hi @visuve ! Thank you for your contribution! It was on my TODO to add Qt6 support, so I really appreciate, it is gonna be very useful.
I just have a doubt about the exact version numbers that you added in the ifdefs:

```
#if QT_VERSION >= QT_VERSION_CHECK(6, 4, 0)
```
and:

```
#if QT_VERSION >= QT_VERSION_CHECK(6, 5, 0)
```
Are you sure that the lower versions of Qt6 don't need them? I tested today with Qt6.2.4 and it actually needed the same ifdefs as the versions above, so the code was not building at first. After I changed to:
```
#if QT_VERSION >= QT_VERSION_CHECK(6, 0, 0)
```
it built fine. So, I have a question - what was the lowest Qt6 version with which you tested?

Regarding the PE-bear, you can send me a pull request of whatever you currently have, and I am gonna take care of the rest. I keep the support for Qt4 because some users explicitly asked me for the backward compatibility, and it was not a big effort to add. The main builds are anyways using Qt5 (and will be switched to Qt6 in upcoming future).

**Comment by visuve** [comment]
@hasherezade you are welcome. I ran with the latest Qt (6.7.0).

For the 6.4.0 see [QMutexLocker](https://doc.qt.io/qt-6/qmutexlocker.html#public-functions) have a look a the small notes on the left hand side of the public constructors. I am not 100% sure whether the earlier ones were templated or not.

For the 6.5.0 see [QDateTime](https://doc.qt.io/qt-6/qdatetime.html#fromSecsSinceEpoch-2). I could use the other version which does not require 6.5.0, but then I would have to include a time zone.

So... I am really confused about the documentation. If you say it built fine with 6.2.4, then there is no point in making these minor version restrictions in the macros. I will make an update asap.

If you can wait till Saturday, I can submit the horrors I faced with the PE-Bear Qt 6.0 migration :D

**Comment by visuve** [comment]
Alright, please have a look at the new commit ;-)

**Comment by hasherezade** [comment]
@visuve - looks good, thank you!
Regarding refactoring PE-bear, TBH, I expected it to be PITA, that's why I kept delaying working on it... 😅 Much appreciated that you took care of it. Even if it is not finished, that's ok.

**Comment by visuve** [comment]
I think the least hacky approach would be to add some sort of compatibility header within the PE-Bear (now that I know that the Qt 4 has to be supported). I will get back to this on Saturday. 

P.s. it is nice to be of use. I love programming, but my own hobby projects (here on GitHub) have pretty much no user base... 😂

**Comment by hasherezade** [comment]
@visuve - I see that you have a quite big collection of cheats for games! That's cool! Cheat authors are always very good reverse engineers :)
Regarding the user base - mine has grown with time. Having Twitter helped me a lot to advertise my projects.

**Comment by visuve** [comment]
@hasherezade nice that you noticed. However I do not consider myself as a good reverse engineer, but I get stuff done when I set my mind to it 😅 

But, speaking of the GameCheats repo, please have a look at the [Hacklib](https://github.com/visuve/GameCheats/tree/master/HackLib) in it. I wrote it myself. Feel free to use bits or pieces from it if you see anything useful 🙂

**Pull request merged**
